[supervisord]
nodaemon=true
logfile=/app/logs/supervisord.log
logfile_maxbytes=10MB

[program:streamlit]
command=streamlit run app/streamlit_app.py --server.port=8501 --server.address=0.0.0.0
directory=/app
autorestart=true
stdout_logfile=/app/logs/streamlit.log
stderr_logfile=/app/logs/streamlit_err.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB

[program:fastapi]
command=uvicorn app.api.main:app --host 0.0.0.0 --port 8000
directory=/app
autorestart=true
stdout_logfile=/app/logs/fastapi.log
stderr_logfile=/app/logs/fastapi_err.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
