#!/usr/bin/env python3
"""
공유 모듈: 디렉토리 매핑, 카테고리 설명, 텍스트 템플릿
Step 4 전처리 파이프라인 전체에서 공용으로 사용
"""
from pathlib import Path

# === 경로 설정 ===
BASE_DIR = Path("/Volumes/Corsair EX300U Media/00_work_out/01_complete/me/01_CAD")
MISUMI_PNG_DIR = BASE_DIR / "CAD_etc" / "data" / "MiSUMi_png"
BEARING_PNG_DIR = BASE_DIR / "CAD_etc" / "data" / "Unit_bearing_png"
STAGED_DIR = BASE_DIR / "drawing-datasets" / "staged"
NORMALIZED_DIR = BASE_DIR / "drawing-datasets" / "normalized"
OUTPUT_DIR = BASE_DIR / "drawing-datasets" / "preprocessed_dataset"

IMAGE_EXTS = {'.png', '.jpg', '.jpeg'}
EXCLUDE_CATEGORIES = {"image_processing", "new_products"}

# === MiSUMi 디렉토리명 → 카테고리명 매핑 (실제 디렉토리명 기준) ===
MISUMI_DIR_MAP = {
    "00_new_products": "new_products",
    "01_Shafts": "Shafts",
    "02_Holders_for_Shaft": "Holders_for_Shaft",
    "03_Set_Collars": "Set_Collars",
    "04_Linear Bushings": "Linear_Bushings",
    "05_Ball_Splines": "Ball_Splines",
    "06_Oil_Free_Bushings": "Oil_Free_Bushings",
    "07_Actuator": "Actuator",
    "08_Linear_Guides": "Linear_Guides",
    "09_Slide_Rails": "Slide_Rails",
    "10_Ball_Screws": "Ball_Screws",
    "11_Slide_Screws": "Slide_Screws",
    "12_Rotary_Shafts": "Rotary_Shafts",
    "13_Hinge_Pins": "Hinge_Pins",
    "14_Bearings_with_Holder": "Bearings_with_Holder",
    "15_Couplings": "Couplings",
    "16_Rollers": "Rollers",
    "17_Conveyors": "Conveyors",
    "18_Flat_Belts_and_Round_Belts": "Flat_Belts_and_Round_Belts",
    "19_Timing_Pulleys": "Timing_Pulleys",
    "20_Gears": "Gears",
    "21_Sprockets_and_Chains": "Sprockets_and_Chains",
    "22_Locating_Pins": "Locating_Pins",
    "23_Locating_&_Guide_Components": "Locating_and_Guide_Components",
    "24_Plungers": "Plungers",
    "25_Clamps": "Clamps",
    "26_Inspections": "Inspections",
    "27_Contact_Probes": "Contact_Probes",
    "28_Simplified Adjustment Units": "Simplified_Adjustment_Units",
    "29_Stages": "Stages",
    "30_image processing": "image_processing",
    "31_Sensors": "Sensors",
    "32_Posts": "Posts",
    "33_Ribs_and_Angle_Plates": "Ribs_and_Angle_Plates",
    "34_Washers": "Washers",
    "35_Screws": "Screws",
    "36_Misc": "Misc",
    "37_Rods": "Rods",
    "38_Springs": "Springs",
    "39_Urethanes": "Urethanes",
    "40_Antivibration": "Antivibration",
    "41_Aluminum_Frames": "Aluminum_Frames",
    "42_Accessories": "Accessories",
    "44_Pipe_Frames": "Pipe_Frames",
    "45_Cover_Panels": "Cover_Panels",
    "46_Resin Plates": "Resin_Plates",
    "47_Led_Lighting": "Led_Lighting",
    "48_Casters": "Casters",
    "49_Levers": "Levers",
    "50_Pulls": "Pulls",
    "51_Manifolds": "Manifolds",
    "52_Pipes_Fitting_Valves": "Pipes_Fitting_Valves",
    "53_Sanitary_Vacuum_Tanks": "Sanitary_Vacuum_Tanks",
    "54_Fitting_and_Nozzles": "Fitting_and_Nozzles",
    "55_Cylinders": "Cylinders",
    "56_Heaters": "Heaters",
    "58_Angles": "Angles",
    "59_Brackets": "Brackets",
}

# === Bearing 디렉토리명 → 카테고리명 매핑 ===
BEARING_DIR_MAP = {
    "1.UCP": "bearing_UCP",
    "2.UKP": "bearing_UKP",
    "3.UCF": "bearing_UCF",
    "5.UCFL": "bearing_UCFL",
    "6.UKFL": "bearing_UKFL",
    "7.UCFC": "bearing_UCFC",
    "8.UKFC": "bearing_UKFC",
    "9.UCFS": "bearing_UCFS",
    "10.UKFS": "bearing_UKFS",
    "11.UCT": "bearing_UCT",
    "12.UKT": "bearing_UKT",
    "13.SN(플러머블록)": "bearing_SN플러머블록",
    "14.TAKEUP": "bearing_TAKEUP",
    "15.H-ADAPTER": "bearing_H_ADAPTER",
}

# === 카테고리별 텍스트 설명 (CLIP 학습용) ===
CATEGORY_DESCRIPTIONS = {
    "Accessories": ["mechanical accessories", "machine accessories and parts"],
    "Actuator": ["actuator mechanism", "linear actuator assembly", "pneumatic actuator"],
    "Aluminum_Frames": ["aluminum extrusion frame", "aluminum structural frame profile"],
    "Angles": ["angle bracket", "metal angle piece", "L-shaped angle"],
    "Antivibration": ["anti-vibration mount", "vibration damper", "rubber anti-vibration pad"],
    "Ball_Screws": ["ball screw assembly", "ball screw with nut", "precision ball screw"],
    "Ball_Splines": ["ball spline shaft", "ball spline bearing assembly"],
    "Bearings_with_Holder": ["bearing unit with housing", "pillow block bearing", "mounted bearing assembly"],
    "Brackets": ["mounting bracket", "structural bracket", "support bracket"],
    "Casters": ["caster wheel", "industrial caster", "swivel caster with brake"],
    "Clamps": ["mechanical clamp", "toggle clamp", "pipe clamp"],
    "Contact_Probes": ["spring contact probe", "test probe pin", "pogo pin"],
    "Conveyors": ["conveyor system", "belt conveyor assembly", "roller conveyor"],
    "Couplings": ["shaft coupling", "flexible coupling", "rigid coupling joint"],
    "Cover_Panels": ["cover panel", "protective cover plate", "enclosure panel"],
    "Cylinders": ["pneumatic cylinder", "hydraulic cylinder", "air cylinder actuator"],
    "Fitting_and_Nozzles": ["pipe fitting", "nozzle connector", "tube fitting"],
    "Flat_Belts_and_Round_Belts": ["flat drive belt", "round belt pulley system"],
    "Gears": ["gear wheel", "spur gear mechanism", "gear assembly"],
    "Heaters": ["industrial heater", "cartridge heater element"],
    "Hinge_Pins": ["hinge pin", "pivot pin", "hinge joint pin"],
    "Holders_for_Shaft": ["shaft holder", "shaft support block", "shaft mounting holder"],
    "Inspections": ["inspection tool", "measurement device", "gauging instrument"],
    "Led_Lighting": ["LED light fixture", "LED illumination module"],
    "Levers": ["mechanical lever", "lever handle", "lever arm mechanism"],
    "Linear_Bushings": ["linear bushing", "linear motion bearing", "slide bushing"],
    "Linear_Guides": ["linear guide rail", "linear motion guide", "precision linear guide"],
    "Locating_Pins": ["locating pin", "dowel pin", "precision locating pin"],
    "Locating_and_Guide_Components": ["guide component", "locating and guide mechanism"],
    "Manifolds": ["manifold block", "pneumatic manifold", "hydraulic manifold"],
    "Misc": ["miscellaneous mechanical part", "various mechanical component"],
    "Oil_Free_Bushings": ["oil-free bushing", "self-lubricating bushing", "dry bushing"],
    "Pipe_Frames": ["pipe frame structure", "tubular frame assembly"],
    "Pipes_Fitting_Valves": ["pipe valve assembly", "pipe fitting and valve", "plumbing valve"],
    "Plungers": ["spring plunger", "ball plunger", "indexing plunger"],
    "Posts": ["support post", "mounting post", "pillar post"],
    "Pulls": ["handle pull", "drawer pull", "cabinet pull handle"],
    "Resin_Plates": ["resin plate", "plastic plate", "polymer sheet"],
    "Ribs_and_Angle_Plates": ["rib plate", "angle plate", "reinforcement rib"],
    "Rods": ["metal rod", "support rod", "guide rod"],
    "Rollers": ["roller", "conveyor roller", "guide roller"],
    "Rotary_Shafts": ["rotary shaft", "rotating shaft", "drive shaft"],
    "Sanitary_Vacuum_Tanks": ["sanitary tank", "vacuum tank vessel", "stainless tank"],
    "Screws": ["machine screw", "fastener screw", "precision screw"],
    "Sensors": ["sensor device", "proximity sensor", "industrial sensor"],
    "Set_Collars": ["set collar", "shaft collar", "clamping collar ring"],
    "Shafts": ["precision shaft", "machine shaft", "drive shaft"],
    "Simplified_Adjustment_Units": ["adjustment unit", "positioning adjustment mechanism"],
    "Slide_Rails": ["slide rail", "drawer slide rail", "linear slide"],
    "Slide_Screws": ["slide screw", "lead screw assembly"],
    "Springs": ["compression spring", "mechanical spring", "coil spring"],
    "Sprockets_and_Chains": ["sprocket wheel", "chain drive sprocket", "roller chain"],
    "Stages": ["positioning stage", "XY stage", "linear stage platform"],
    "Timing_Pulleys": ["timing belt pulley", "synchronous pulley", "toothed pulley"],
    "Urethanes": ["urethane component", "polyurethane part", "urethane rubber"],
    "Washers": ["flat washer", "spring washer", "lock washer"],
    # Bearing
    "bearing_UCP": ["UCP pillow block bearing", "UCP pedestal bearing unit"],
    "bearing_UKP": ["UKP pillow block bearing", "UKP adapter sleeve bearing"],
    "bearing_UCF": ["UCF square flange bearing", "UCF 4-bolt flange bearing"],
    "bearing_UCFL": ["UCFL two-bolt flange bearing", "UCFL oval flange bearing"],
    "bearing_UKFL": ["UKFL two-bolt flange bearing", "UKFL oval flange adapter"],
    "bearing_UCFC": ["UCFC piloted flange bearing", "UCFC round cartridge bearing"],
    "bearing_UKFC": ["UKFC piloted flange bearing", "UKFC round cartridge adapter"],
    "bearing_UCFS": ["UCFS piloted flange bearing", "UCFS square cartridge bearing"],
    "bearing_UKFS": ["UKFS piloted flange bearing", "UKFS square cartridge adapter"],
    "bearing_UCT": ["UCT take-up bearing", "UCT sliding block bearing"],
    "bearing_UKT": ["UKT take-up bearing", "UKT sliding block adapter"],
    "bearing_SN플러머블록": ["SN plummer block bearing", "SN split bearing housing"],
    "bearing_TAKEUP": ["take-up bearing unit", "conveyor take-up bearing"],
    "bearing_H_ADAPTER": ["H adapter sleeve", "bearing adapter sleeve"],
    # 신규 (Patent/Staged)
    "Wheels": ["wheel rim", "vehicle wheel", "automotive wheel"],
    "Tires": ["tire cross-section", "rubber tire", "vehicle tire"],
    "Suspension": ["suspension system", "vehicle suspension assembly", "shock absorber"],
    "Brakes": ["brake assembly", "disc brake system", "brake caliper"],
    "Powertrain": ["powertrain component", "transmission system", "drivetrain assembly"],
    "Clutches": ["clutch mechanism", "friction clutch assembly", "clutch plate"],
    "Pistons": ["engine piston", "piston assembly", "cylinder piston"],
    "Differential": ["differential gear", "differential mechanism", "axle differential"],
    "Bolts_and_Nuts": ["bolt and nut", "hex bolt fastener", "threaded fastener"],
    "Flanges": ["pipe flange", "flange connection", "mounting flange"],
    "Housing": ["mechanical housing", "bearing housing", "gear housing enclosure"],
    "Airbag_Module": ["airbag module", "airbag inflator assembly", "vehicle airbag unit"],
}

# === CLIP 학습용 텍스트 템플릿 ===
TEXT_TEMPLATES = [
    "a technical drawing of {}",
    "an engineering drawing of {}",
    "a CAD blueprint showing {}",
    "a mechanical drawing of {}",
    "a 2D technical illustration of {}",
    "engineering blueprint of {}",
    "industrial drawing showing {}",
    "technical specification drawing of {}",
]
