"""Gate reviewed supplement brand decisions before DB import.

This script consumes the redacted output from
``preflight_supplement_brand_review_decisions.py`` and decides whether the next
step may build a reviewed product import manifest. It intentionally does not
read decision JSONL rows, source images, OCR text, provider payloads, LLM
outputs, or database records.

The gate is stricter than partial apply readiness: DB import preparation is
allowed only when the brand decision preflight was run with strict review
requirements and every brand candidate has a valid non-blank decision.

References:
    https://docs.python.org/3/library/argparse.html
    https://docs.python.org/3/library/json.html
    https://www.postgresql.org/docs/current/ddl-constraints.html
    https://supabase.com/docs/guides/database/postgres/row-level-security
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from collections.abc import Mapping
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

BACKEND_ROOT = Path(__file__).resolve().parents[1]
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

from scripts import preflight_supplement_brand_review_decisions as brand_preflight  # noqa: E402

SCHEMA_VERSION = "supplement-brand-db-import-gate-v1"
BRAND_PREFLIGHT_SCHEMA_VERSION = brand_preflight.SCHEMA_VERSION
SOURCE_DOC_URLS = (
    "https://docs.python.org/3/library/argparse.html",
    "https://docs.python.org/3/library/json.html",
    "https://www.postgresql.org/docs/current/ddl-constraints.html",
    "https://supabase.com/docs/guides/database/postgres/row-level-security",
)
READY_STATUS = "ready_for_product_import_manifest"
BLOCKED_STATUS = "blocked_by_operator_review"
ERROR_STATUS = "error"
READY_NEXT_STEPS = (
    "run_apply_supplement_brand_review_decisions_require_all_reviewed",
    "run_taxonomy_approved_manifest_import_dry_run_require_approved_products",
    "run_taxonomy_approved_manifest_db_apply_only_after_dry_run_ready",
)
BLOCKED_NEXT_STEPS = (
    "complete_operator_brand_review",
    "rerun_brand_decision_preflight_require_all_reviewed",
    "rerun_brand_db_import_gate",
)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parse command-line arguments.

    Args:
        argv: Optional argument list for tests.

    Returns:
        Parsed CLI namespace.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--brand-decision-preflight", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--markdown-output", type=Path, default=None)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> None:
    """Write a redacted brand DB import gate report.

    Args:
        argv: Optional argument list for tests.
    """
    args = parse_args(argv)
    preflight_path = args.brand_decision_preflight.expanduser().resolve()
    output_path = args.output.expanduser().resolve()
    markdown_output = (
        args.markdown_output.expanduser().resolve() if args.markdown_output is not None else None
    )
    try:
        summary = build_brand_db_import_gate(brand_decision_preflight=preflight_path)
        _write_json(output_path, summary)
        if markdown_output is not None:
            markdown_output.parent.mkdir(parents=True, exist_ok=True)
            markdown_output.write_text(build_markdown(summary), encoding="utf-8")
        print(json.dumps(_cli_summary(summary), ensure_ascii=False, sort_keys=True))
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        failure = _failure_summary(
            preflight_path=preflight_path, output_path=output_path, error=exc
        )
        _write_json(output_path, failure)
        print(json.dumps(failure, ensure_ascii=False, sort_keys=True))
        raise SystemExit(1) from None


def build_brand_db_import_gate(*, brand_decision_preflight: Path) -> dict[str, Any]:
    """Build a redacted gate summary from brand decision preflight output.

    Args:
        brand_decision_preflight: JSON generated by brand decision preflight.

    Returns:
        Redacted gate summary.

    Raises:
        ValueError: If the preflight artifact is unsafe or unsupported.
    """
    payload = _load_json_object(brand_decision_preflight)
    _reject_unsafe_payload(payload)
    if payload.get("schema_version") != BRAND_PREFLIGHT_SCHEMA_VERSION:
        raise ValueError("Brand decision preflight uses an unsupported schema.")

    counts = _extract_counts(payload)
    strict_review_requested = payload.get("require_all_reviewed") is True
    ready_for_strict_apply = payload.get("ready_for_strict_apply") is True
    ready_for_requested_apply = payload.get("ready_for_requested_apply") is True
    no_pending_or_invalid = all(
        counts[key] == 0
        for key in (
            "blank_decision_count",
            "invalid_decision_count",
            "unmatched_decision_count",
            "missing_decision_count",
            "pending_operator_action_count",
        )
    )
    has_approved_rows = counts["approved_decision_count"] > 0
    allow_product_manifest = (
        strict_review_requested
        and ready_for_strict_apply
        and ready_for_requested_apply
        and no_pending_or_invalid
        and has_approved_rows
    )
    status = READY_STATUS if allow_product_manifest else BLOCKED_STATUS
    next_steps = list(READY_NEXT_STEPS if allow_product_manifest else BLOCKED_NEXT_STEPS)

    summary = {
        "schema_version": SCHEMA_VERSION,
        "status": status,
        "generated_at": datetime.now(UTC).isoformat(),
        "brand_decision_preflight_name": brand_decision_preflight.name,
        "brand_decision_preflight_hash": _fingerprint_file(brand_decision_preflight),
        "brand_candidate_count": counts["brand_candidate_count"],
        "decision_row_count": counts["decision_row_count"],
        "valid_decision_count": counts["valid_decision_count"],
        "approved_decision_count": counts["approved_decision_count"],
        "blank_decision_count": counts["blank_decision_count"],
        "invalid_decision_count": counts["invalid_decision_count"],
        "unmatched_decision_count": counts["unmatched_decision_count"],
        "missing_decision_count": counts["missing_decision_count"],
        "pending_operator_action_count": counts["pending_operator_action_count"],
        "strict_review_requested": strict_review_requested,
        "ready_for_strict_apply": ready_for_strict_apply,
        "ready_for_requested_apply": ready_for_requested_apply,
        "product_import_manifest_allowed": allow_product_manifest,
        "db_import_apply_allowed_now": False,
        "db_import_apply_allowed_after_dry_run": allow_product_manifest,
        "next_operator_action": _safe_token(
            str(payload.get("next_operator_action") or "complete_operator_brand_review")
        ),
        "next_steps": next_steps,
        "db_write_performed": False,
        "ocr_provider_call_performed": False,
        "llm_call_performed": False,
        "source_rows_read": False,
        "source_image_read_performed": False,
        "raw_ocr_text_stored": False,
        "raw_provider_payload_stored": False,
        "absolute_paths_stored": False,
        "product_dir_literals_stored": False,
        "local_path_literals_stored": False,
        "source_doc_urls": list(SOURCE_DOC_URLS),
    }
    _reject_unsafe_payload(summary)
    return summary


def build_markdown(summary: Mapping[str, Any]) -> str:
    """Build a redacted Markdown gate report.

    Args:
        summary: Gate summary.

    Returns:
        Markdown text.
    """
    _reject_unsafe_payload(summary)
    next_steps = "\n".join(f"- `{_safe_token(str(step))}`" for step in summary["next_steps"])
    markdown = "\n".join(
        [
            "# Supplement Brand DB Import Gate",
            "",
            f"Schema: `{SCHEMA_VERSION}`",
            "",
            "## Status",
            "",
            f"- Status: `{_safe_token(str(summary['status']))}`",
            f"- Product import manifest allowed: `{str(summary['product_import_manifest_allowed']).lower()}`",
            f"- DB apply allowed now: `{str(summary['db_import_apply_allowed_now']).lower()}`",
            f"- DB apply allowed after dry-run: `{str(summary['db_import_apply_allowed_after_dry_run']).lower()}`",
            "",
            "## Counts",
            "",
            f"- Brand candidates: `{_non_negative_int(summary['brand_candidate_count'])}`",
            f"- Decision rows: `{_non_negative_int(summary['decision_row_count'])}`",
            f"- Valid decisions: `{_non_negative_int(summary['valid_decision_count'])}`",
            f"- Approved decisions: `{_non_negative_int(summary['approved_decision_count'])}`",
            f"- Blank decisions: `{_non_negative_int(summary['blank_decision_count'])}`",
            f"- Invalid decisions: `{_non_negative_int(summary['invalid_decision_count'])}`",
            f"- Unmatched decisions: `{_non_negative_int(summary['unmatched_decision_count'])}`",
            f"- Missing decisions: `{_non_negative_int(summary['missing_decision_count'])}`",
            f"- Pending operator actions: `{_non_negative_int(summary['pending_operator_action_count'])}`",
            "",
            "## Next Steps",
            "",
            next_steps,
            "",
            "## Rule",
            "",
            "DB apply는 지금 바로 허용하지 않습니다. strict brand review preflight 통과 후 product import manifest를 만들고, taxonomy approved manifest dry-run이 먼저 통과해야 합니다.",
            "",
        ]
    )
    _reject_unsafe_payload(markdown)
    return markdown


def _extract_counts(payload: Mapping[str, Any]) -> dict[str, int]:
    """Extract non-negative aggregate counts from a preflight payload.

    Args:
        payload: Brand decision preflight payload.

    Returns:
        Count mapping.
    """
    keys = (
        "brand_candidate_count",
        "decision_row_count",
        "valid_decision_count",
        "approved_decision_count",
        "blank_decision_count",
        "invalid_decision_count",
        "unmatched_decision_count",
        "missing_decision_count",
        "pending_operator_action_count",
    )
    return {key: _non_negative_int(payload.get(key)) for key in keys}


def _load_json_object(path: Path) -> dict[str, Any]:
    """Load one JSON object from disk.

    Args:
        path: JSON file path.

    Returns:
        Parsed JSON object.

    Raises:
        ValueError: If the file does not contain one JSON object.
    """
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("Brand DB import gate input must be a JSON object.")
    return payload


def _non_negative_int(value: Any) -> int:
    """Return a non-negative integer.

    Args:
        value: Candidate value.

    Returns:
        Non-negative integer.

    Raises:
        ValueError: If the value is not a non-negative integer.
    """
    if not isinstance(value, int) or value < 0:
        raise ValueError("Expected a non-negative integer.")
    return value


def _safe_token(value: str) -> str:
    """Return a safe token.

    Args:
        value: Candidate token.

    Returns:
        Safe token.
    """
    return brand_preflight.applier._required_safe_token(value, field_name="token")


def _reject_unsafe_payload(value: Any) -> None:
    """Reject raw OCR/provider payloads and local path literals.

    Args:
        value: Candidate JSON-like value.
    """
    brand_preflight.applier._reject_unsafe_payload(value)


def _sha256_file(path: Path) -> str:
    """Return the SHA-256 digest for a file.

    Args:
        path: File path.

    Returns:
        Hex digest.
    """
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _fingerprint_file(path: Path) -> str:
    """Return a short public fingerprint for a local artifact.

    Args:
        path: File path.

    Returns:
        Short fingerprint safe for public reports.
    """
    return f"fp-{_sha256_file(path)[:12]}"


def _write_json(path: Path, payload: Mapping[str, Any]) -> None:
    """Write one JSON object.

    Args:
        path: Destination path.
        payload: JSON payload.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def _cli_summary(summary: Mapping[str, Any]) -> dict[str, Any]:
    """Return a compact CLI-safe summary.

    Args:
        summary: Full gate summary.

    Returns:
        CLI summary.
    """
    return {
        "schema_version": SCHEMA_VERSION,
        "status": summary["status"],
        "brand_candidate_count": summary["brand_candidate_count"],
        "approved_decision_count": summary["approved_decision_count"],
        "blank_decision_count": summary["blank_decision_count"],
        "pending_operator_action_count": summary["pending_operator_action_count"],
        "product_import_manifest_allowed": summary["product_import_manifest_allowed"],
        "db_import_apply_allowed_now": False,
        "db_import_apply_allowed_after_dry_run": summary["db_import_apply_allowed_after_dry_run"],
    }


def _failure_summary(
    *,
    preflight_path: Path,
    output_path: Path,
    error: Exception,
) -> dict[str, Any]:
    """Return a redacted failure summary.

    Args:
        preflight_path: Input preflight path.
        output_path: Planned output path.
        error: Raised exception.

    Returns:
        Redacted failure payload.
    """
    _ = error
    summary = {
        "schema_version": SCHEMA_VERSION,
        "status": ERROR_STATUS,
        "generated_at": datetime.now(UTC).isoformat(),
        "brand_decision_preflight_name": preflight_path.name,
        "output_name": output_path.name,
        "product_import_manifest_allowed": False,
        "db_import_apply_allowed_now": False,
        "db_import_apply_allowed_after_dry_run": False,
        "db_write_performed": False,
        "ocr_provider_call_performed": False,
        "llm_call_performed": False,
        "source_rows_read": False,
        "source_image_read_performed": False,
        "raw_ocr_text_stored": False,
        "raw_provider_payload_stored": False,
        "absolute_paths_stored": False,
        "product_dir_literals_stored": False,
        "local_path_literals_stored": False,
    }
    _reject_unsafe_payload(summary)
    return summary


if __name__ == "__main__":
    main()
