"""Build a redacted cleanup preflight for supplement category seed drift.

This tool compares the expected category seed rows from the crawling-image
taxonomy staging manifest with active ``supplement_categories`` keys observed in
the database. It never writes to the database. The output intentionally keeps
category keys hash-only so operators can prove drift without exposing source
folder labels in shared logs.

References:
    https://www.postgresql.org/docs/current/ddl-constraints.html
    https://docs.sqlalchemy.org/en/21/orm/queryguide/select.html
    https://supabase.com/docs/guides/database/postgres/row-level-security
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

BACKEND_ROOT = Path(__file__).resolve().parents[1]
if str(BACKEND_ROOT) not in sys.path:
    sys.path.insert(0, str(BACKEND_ROOT))

from scripts import import_supplement_taxonomy_approved_manifest as importer  # noqa: E402

SCHEMA_VERSION = "supplement-category-seed-cleanup-preflight-v1"
SOURCE_DOC_URLS = (
    "https://www.postgresql.org/docs/current/ddl-constraints.html",
    "https://docs.sqlalchemy.org/en/21/orm/queryguide/select.html",
    "https://supabase.com/docs/guides/database/postgres/row-level-security",
)
LOCAL_PATH_MARKERS = (
    "/private/",
    "/Users/",
    "/Volumes/",
    "file://",
    "\\Users\\",
    "\\Volumes\\",
)
RAW_FORBIDDEN_KEYS = frozenset(
    {
        "api_key",
        "authorization",
        "database_url",
        "image_bytes",
        "ocr_text",
        "owner_hash",
        "provider_payload",
        "raw_image",
        "raw_ocr_text",
        "raw_provider_payload",
        "request_headers",
        "service_key",
    }
)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parse command-line arguments.

    Args:
        argv: Optional argument list for tests.

    Returns:
        Parsed CLI namespace.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--taxonomy-staging", type=Path, required=True)
    parser.add_argument(
        "--active-category-dump",
        type=Path,
        required=True,
        help="One active category_key per line from a read-only DB query.",
    )
    parser.add_argument("--summary", type=Path, required=True)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> None:
    """Run CLI entrypoint.

    Args:
        argv: Optional argument list for tests.
    """
    raise SystemExit(run_cli(argv))


def run_cli(argv: list[str] | None = None) -> int:
    """Run category cleanup preflight and print a redacted summary.

    Args:
        argv: Optional argument list for tests.

    Returns:
        Process exit code.
    """
    args = parse_args(argv)
    try:
        summary = build_category_seed_cleanup_preflight(
            taxonomy_staging=args.taxonomy_staging.expanduser().resolve(),
            active_category_dump=args.active_category_dump.expanduser().resolve(),
        )
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        summary = _failure_summary(
            taxonomy_staging=args.taxonomy_staging,
            active_category_dump=args.active_category_dump,
            error=exc,
        )
        _write_summary(args.summary.expanduser().resolve(), summary)
        print(json.dumps(summary, ensure_ascii=False, indent=2, sort_keys=True))
        return 1

    _write_summary(args.summary.expanduser().resolve(), summary)
    print(json.dumps(summary, ensure_ascii=False, indent=2, sort_keys=True))
    return 0


def build_category_seed_cleanup_preflight(
    *,
    taxonomy_staging: Path,
    active_category_dump: Path,
) -> dict[str, Any]:
    """Compare expected category seed rows with active DB category keys.

    Args:
        taxonomy_staging: JSONL generated by taxonomy DB staging.
        active_category_dump: Read-only DB dump with one active category key per line.

    Returns:
        Redacted cleanup preflight summary.

    Raises:
        ValueError: If inputs are empty, malformed, or unsafe.
    """
    category_rows = importer._category_rows_by_key(
        importer._read_jsonl_objects(taxonomy_staging)
    )
    expected_keys = set(category_rows)
    active_keys = _read_active_category_dump(active_category_dump)
    missing_keys = sorted(expected_keys - active_keys)
    extra_keys = sorted(active_keys - expected_keys)
    matched_keys = sorted(expected_keys.intersection(active_keys))

    exact_match = not missing_keys and not extra_keys
    cleanup_required = bool(extra_keys)
    summary = {
        "schema_version": SCHEMA_VERSION,
        "generated_at": datetime.now(UTC).isoformat(),
        "status": _status(exact_match=exact_match, missing_keys=missing_keys, extra_keys=extra_keys),
        "taxonomy_staging_name": taxonomy_staging.name,
        "taxonomy_staging_sha256": _sha256_file(taxonomy_staging),
        "active_category_dump_name": active_category_dump.name,
        "active_category_dump_sha256": _sha256_file(active_category_dump),
        "expected_category_count": len(expected_keys),
        "active_db_category_count": len(active_keys),
        "matched_category_count": len(matched_keys),
        "missing_category_count": len(missing_keys),
        "extra_active_category_count": len(extra_keys),
        "missing_category_key_hashes": [_hash_text(key) for key in missing_keys],
        "extra_active_category_key_hashes": [_hash_text(key) for key in extra_keys],
        "category_seed_exact_match": exact_match,
        "cleanup_required": cleanup_required,
        "cleanup_requires_manual_approval": cleanup_required,
        "cleanup_plan": {
            "target_table": "supplement_categories",
            "operation": "deactivate_extra_active_categories",
            "selector": "extra_active_category_key_hashes",
            "manual_approval_required": cleanup_required,
            "safe_without_operator_review": False,
        },
        "db_write_performed": False,
        "db_delete_performed": False,
        "db_update_performed": False,
        "raw_ocr_text_stored": False,
        "raw_provider_payload_stored": False,
        "local_paths_printed": False,
        "category_literals_printed": False,
        "product_names_printed": False,
        "manufacturer_names_printed": False,
        "source_doc_urls": list(SOURCE_DOC_URLS),
    }
    _reject_unsafe_payload(summary)
    return summary


def _read_active_category_dump(path: Path) -> set[str]:
    """Read active category keys from a plain text dump.

    Args:
        path: Text file with one category key per line.

    Returns:
        Active category key set.

    Raises:
        ValueError: If the dump is empty or contains unsafe values.
    """
    rows = {
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    }
    if not rows:
        raise ValueError("active category dump is empty.")
    for row in rows:
        if any(marker in row for marker in LOCAL_PATH_MARKERS):
            raise ValueError("active category dump contains an unsafe path marker.")
    return rows


def _status(*, exact_match: bool, missing_keys: list[str], extra_keys: list[str]) -> str:
    """Return a stable cleanup preflight status."""
    if exact_match:
        return "no_cleanup_required"
    if missing_keys and extra_keys:
        return "blocked_category_seed_mismatch"
    if missing_keys:
        return "blocked_missing_expected_categories"
    return "manual_cleanup_required"


def _failure_summary(
    *,
    taxonomy_staging: Path,
    active_category_dump: Path,
    error: Exception,
) -> dict[str, Any]:
    """Build a redacted failure summary."""
    return {
        "schema_version": SCHEMA_VERSION,
        "generated_at": datetime.now(UTC).isoformat(),
        "status": "error",
        "taxonomy_staging_name": taxonomy_staging.name,
        "active_category_dump_name": active_category_dump.name,
        "taxonomy_staging_path_hash": _hash_text(str(taxonomy_staging.expanduser())),
        "active_category_dump_path_hash": _hash_text(str(active_category_dump.expanduser())),
        "error_type": type(error).__name__,
        "db_write_performed": False,
        "db_delete_performed": False,
        "db_update_performed": False,
        "raw_ocr_text_stored": False,
        "raw_provider_payload_stored": False,
        "local_paths_printed": False,
        "category_literals_printed": False,
    }


def _write_summary(path: Path, summary: dict[str, Any]) -> None:
    """Write a summary JSON file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(summary, ensure_ascii=False, indent=2, sort_keys=True) + "\n")


def _hash_text(value: str) -> str:
    """Return a stable short SHA-256 hash for a text value."""
    return hashlib.sha256(value.encode("utf-8")).hexdigest()[:16]


def _sha256_file(path: Path) -> str:
    """Return SHA-256 for a file."""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _reject_unsafe_payload(payload: Any) -> None:
    """Reject summaries that expose local paths or raw/private payload fields."""
    serialized = json.dumps(payload, ensure_ascii=False, sort_keys=True)
    if any(marker in serialized for marker in LOCAL_PATH_MARKERS):
        raise ValueError("summary contains an unsafe local path marker.")
    lowered = serialized.lower()
    for key in RAW_FORBIDDEN_KEYS:
        if f'"{key}"' in lowered:
            raise ValueError("summary contains a forbidden raw/private key.")


if __name__ == "__main__":
    main()
