"""Meal image API contract routes."""

from __future__ import annotations

from datetime import datetime
from typing import Annotated, Any
from uuid import UUID

from fastapi import (
    APIRouter,
    Body,
    Depends,
    File,
    Form,
    HTTPException,
    Query,
    Request,
    UploadFile,
    status,
)
from sqlalchemy.ext.asyncio import AsyncSession

from src.api.v1.contract import P1_2_INTAKE_READY_STATUS, route_contract
from src.api.v1.examples import (
    INSUFFICIENT_SCOPE_EXAMPLE,
    PAYLOAD_TOO_LARGE_EXAMPLE,
    UNAUTHORIZED_EXAMPLE,
    UNPROCESSABLE_ENTITY_EXAMPLE,
    UNSUPPORTED_MEDIA_TYPE_EXAMPLE,
)
from src.config import Settings, get_settings
from src.db.dependencies import get_async_session
from src.models.schemas.meal import (
    MealConfirmationRequest,
    MealImageAnalysisPreview,
    MealRecordListResponse,
    MealRecordResponse,
    MealType,
)
from src.models.schemas.privacy import ConsentType
from src.models.schemas.taxonomy import FoodCatalogItemListResponse, FoodCuisineListResponse
from src.security.auth import AuthenticatedUser, require_meal_read, require_meal_write
from src.security.scopes import ApiScope
from src.services.meal_image_analysis import (
    MealConfirmationValidationError,
    MealImageAnalysisConflictError,
    MealImageValidationError,
    MealPreviewNotFoundError,
    MealPreviewStateError,
    confirm_meal_record_from_preview,
    create_meal_image_analysis_preview,
    list_user_meal_records,
    meal_confirmation_to_response,
    meal_image_analysis_to_preview,
    read_and_validate_meal_image,
)
from src.services.privacy import (
    ConsentRequiredError,
    record_sensitive_audit_event,
    require_user_consent,
)
from src.services.taxonomy_catalog import (
    TaxonomyFilterNotFoundError,
    list_food_catalog_items,
    list_food_cuisines,
)

router = APIRouter(prefix="/meals", tags=["meals"])

__all__ = ["router"]

MEAL_AUTH_RESPONSES: dict[int | str, dict[str, Any]] = {
    401: {"content": {"application/json": {"examples": UNAUTHORIZED_EXAMPLE}}},
    403: {"content": {"application/json": {"examples": INSUFFICIENT_SCOPE_EXAMPLE}}},
    422: {"content": {"application/json": {"examples": UNPROCESSABLE_ENTITY_EXAMPLE}}},
}


async def _commit_consent_read_transaction(session: AsyncSession) -> None:
    """Close an implicit consent-read transaction before service-level writes.

    Args:
        session: Request-scoped async database session.
    """
    in_transaction = getattr(session, "in_transaction", None)
    if callable(in_transaction) and in_transaction():
        await session.commit()


@router.post(
    "/analyze-image",
    response_model=MealImageAnalysisPreview,
    status_code=status.HTTP_202_ACCEPTED,
    responses={
        **MEAL_AUTH_RESPONSES,
        202: {"description": "Food image preview requiring user confirmation."},
        413: {"content": {"application/json": {"examples": PAYLOAD_TOO_LARGE_EXAMPLE}}},
        409: {
            "description": "client_request_id was already used for different image bytes.",
        },
        415: {"content": {"application/json": {"examples": UNSUPPORTED_MEDIA_TYPE_EXAMPLE}}},
    },
    openapi_extra=route_contract(
        scopes=(ApiScope.MEAL_WRITE,),
        consents=(ConsentType.FOOD_IMAGE_PROCESSING,),
        contract_status=P1_2_INTAKE_READY_STATUS,
    ),
)
async def analyze_meal_image(
    http_request: Request,
    current_user: Annotated[AuthenticatedUser, Depends(require_meal_write)],
    image: Annotated[UploadFile, File(description="Food or meal image file.")],
    session: Annotated[AsyncSession, Depends(get_async_session)],
    settings: Annotated[Settings, Depends(get_settings)],
    client_request_id: Annotated[str | None, Form(max_length=80)] = None,
    meal_type: Annotated[MealType, Form()] = MealType.UNKNOWN,
    eaten_at: Annotated[datetime | None, Form()] = None,
) -> MealImageAnalysisPreview:
    """Create a food image preview that must be completed or confirmed by the user.

    Args:
        http_request: Current FastAPI request.
        current_user: Authenticated owner.
        image: Uploaded food image.
        session: Request-scoped async database session.
        settings: Application settings.
        client_request_id: Optional idempotency key generated by the client.
        meal_type: User-selected meal bucket.
        eaten_at: Optional user-selected meal timestamp.

    Returns:
        Food image analysis preview requiring user confirmation.

    Raises:
        HTTPException: If consent is missing, image validation fails, or idempotency conflicts.
    """
    try:
        await require_user_consent(session, current_user, ConsentType.FOOD_IMAGE_PROCESSING)
    except ConsentRequiredError as exc:
        await record_sensitive_audit_event(
            session,
            current_user,
            action="meal_image_intake_blocked",
            resource_type="food_image_analysis_run",
            resource_id=None,
            outcome="blocked",
            request=http_request,
            settings=settings,
            event_metadata={"missing_consents": [ConsentType.FOOD_IMAGE_PROCESSING.value]},
        )
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail={
                "code": "consent_required",
                "message": str(exc),
                "required_consents": [ConsentType.FOOD_IMAGE_PROCESSING.value],
            },
        ) from exc

    await _commit_consent_read_transaction(session)

    try:
        image_metadata = await read_and_validate_meal_image(image, settings)
        result = await create_meal_image_analysis_preview(
            session=session,
            user=current_user,
            image_metadata=image_metadata,
            meal_type=meal_type,
            eaten_at=eaten_at,
            client_request_id=client_request_id,
            settings=settings,
        )
    except MealImageValidationError as exc:
        await record_sensitive_audit_event(
            session,
            current_user,
            action="meal_image_intake_rejected",
            resource_type="food_image_analysis_run",
            resource_id=None,
            outcome="blocked",
            request=http_request,
            settings=settings,
            event_metadata={"validation_code": exc.code},
        )
        raise HTTPException(
            status_code=exc.status_code,
            detail={"code": exc.code, "message": exc.message},
        ) from exc
    except MealImageAnalysisConflictError as exc:
        await record_sensitive_audit_event(
            session,
            current_user,
            action="meal_image_intake_conflict",
            resource_type="food_image_analysis_run",
            resource_id=None,
            outcome="blocked",
            request=http_request,
            settings=settings,
            event_metadata={"client_request_id_present": bool(client_request_id)},
        )
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail={
                "code": "idempotency_conflict",
                "message": str(exc),
            },
        ) from exc

    preview = meal_image_analysis_to_preview(result)

    await record_sensitive_audit_event(
        session,
        current_user,
        action=(
            "meal_image_intake_reused" if result.reused_existing else "meal_image_intake_created"
        ),
        resource_type="food_image_analysis_run",
        resource_id=str(result.analysis_run.id),
        outcome="success",
        request=http_request,
        settings=settings,
        event_metadata={
            "client_request_id_present": bool(client_request_id),
            "image_mime_type": result.image_metadata.mime_type,
            "image_size_bytes": result.image_metadata.size_bytes,
            "meal_type": meal_type.value,
            "reused_existing": result.reused_existing,
            "detector_used": preview.pipeline_metadata.detector_used,
            "classifier_used": preview.pipeline_metadata.classifier_used,
            "raw_image_stored": False,
            "raw_provider_payload_stored": False,
        },
    )
    return preview


@router.get(
    "/cuisines",
    response_model=FoodCuisineListResponse,
    responses={**MEAL_AUTH_RESPONSES},
    openapi_extra=route_contract(
        scopes=(ApiScope.MEAL_READ,),
        consents=(),
        contract_status=P1_2_INTAKE_READY_STATUS,
    ),
)
async def list_food_cuisine_catalog(
    current_user: Annotated[AuthenticatedUser, Depends(require_meal_read)],
    session: Annotated[AsyncSession, Depends(get_async_session)],
) -> FoodCuisineListResponse:
    """List active food cuisines and nested courses for meal filter UIs.

    Args:
        current_user: Authenticated caller; only used to enforce read scope.
        session: Request-scoped async database session.

    Returns:
        Active food cuisine catalog response.
    """
    del current_user
    return await list_food_cuisines(session)


@router.get(
    "/foods",
    response_model=FoodCatalogItemListResponse,
    responses={**MEAL_AUTH_RESPONSES},
    openapi_extra=route_contract(
        scopes=(ApiScope.MEAL_READ,),
        consents=(),
        contract_status=P1_2_INTAKE_READY_STATUS,
    ),
)
async def list_food_catalog(
    current_user: Annotated[AuthenticatedUser, Depends(require_meal_read)],
    session: Annotated[AsyncSession, Depends(get_async_session)],
    cuisine_code: Annotated[str | None, Query(max_length=40)] = None,
    course_code: Annotated[str | None, Query(max_length=60)] = None,
    q: Annotated[str | None, Query(max_length=120)] = None,
    limit: Annotated[int, Query(ge=1, le=100)] = 50,
    offset: Annotated[int, Query(ge=0)] = 0,
) -> FoodCatalogItemListResponse:
    """List active food catalog items for selection UIs.

    Args:
        current_user: Authenticated caller; only used to enforce read scope.
        session: Request-scoped async database session.
        cuisine_code: Optional active cuisine code filter.
        course_code: Optional active course code filter.
        q: Optional canonical food name substring.
        limit: Maximum result count.
        offset: Result offset.

    Returns:
        Paginated active food catalog item response.
    """
    del current_user
    return await list_food_catalog_items(
        session,
        cuisine_code=cuisine_code,
        course_code=course_code,
        q=q,
        limit=limit,
        offset=offset,
    )


@router.get(
    "",
    response_model=MealRecordListResponse,
    responses={**MEAL_AUTH_RESPONSES},
    openapi_extra=route_contract(
        scopes=(ApiScope.MEAL_READ,),
        consents=(),
        contract_status=P1_2_INTAKE_READY_STATUS,
    ),
)
async def list_meal_records(
    http_request: Request,
    current_user: Annotated[AuthenticatedUser, Depends(require_meal_read)],
    session: Annotated[AsyncSession, Depends(get_async_session)],
    settings: Annotated[Settings, Depends(get_settings)],
    cuisine_code: Annotated[str | None, Query(max_length=40)] = None,
    course_code: Annotated[str | None, Query(max_length=60)] = None,
    food_catalog_item_id: Annotated[UUID | None, Query()] = None,
    from_eaten_at: Annotated[datetime | None, Query()] = None,
    to_eaten_at: Annotated[datetime | None, Query()] = None,
    limit: Annotated[int, Query(ge=1, le=100)] = 20,
    offset: Annotated[int, Query(ge=0)] = 0,
) -> MealRecordListResponse:
    """List current-user confirmed meals with optional taxonomy filters.

    Args:
        http_request: Current FastAPI request.
        current_user: Authenticated owner.
        session: Request-scoped async database session.
        settings: Application settings.
        cuisine_code: Optional active cuisine code filter.
        course_code: Optional active course code filter.
        food_catalog_item_id: Optional active food catalog item filter.
        from_eaten_at: Optional inclusive lower eaten-at timestamp.
        to_eaten_at: Optional inclusive upper eaten-at timestamp.
        limit: Maximum result count.
        offset: Result offset.

    Returns:
        Paginated current-user confirmed meal records.

    Raises:
        HTTPException: If taxonomy filters are stale or timestamp range is invalid.
    """
    try:
        response = await list_user_meal_records(
            session=session,
            user=current_user,
            limit=limit,
            offset=offset,
            cuisine_code=cuisine_code,
            course_code=course_code,
            food_catalog_item_id=food_catalog_item_id,
            from_eaten_at=from_eaten_at,
            to_eaten_at=to_eaten_at,
        )
    except TaxonomyFilterNotFoundError as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_CONTENT,
            detail={"code": "taxonomy_filter_not_found", "message": str(exc)},
        ) from exc
    except ValueError as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_CONTENT,
            detail={"code": "invalid_meal_query", "message": str(exc)},
        ) from exc

    await record_sensitive_audit_event(
        session,
        current_user,
        action="meal_listed",
        resource_type="meal_record",
        resource_id=None,
        outcome="success",
        request=http_request,
        settings=settings,
        event_metadata={
            "count": len(response.results),
            "limit": limit,
            "offset": offset,
            "cuisine_code_present": cuisine_code is not None,
            "course_code_present": course_code is not None,
            "food_catalog_item_id_present": food_catalog_item_id is not None,
            "from_eaten_at_present": from_eaten_at is not None,
            "to_eaten_at_present": to_eaten_at is not None,
        },
    )
    return response


@router.post(
    "/{meal_id}/confirm",
    response_model=MealRecordResponse,
    status_code=status.HTTP_200_OK,
    responses={
        **MEAL_AUTH_RESPONSES,
        200: {"description": "Food image preview confirmed by the user."},
        404: {"description": "Meal preview was not found for the current user."},
        409: {"description": "Meal preview state does not allow confirmation."},
    },
    openapi_extra=route_contract(
        scopes=(ApiScope.MEAL_WRITE,),
        consents=(),
        contract_status=P1_2_INTAKE_READY_STATUS,
    ),
)
async def confirm_meal_image_preview(
    meal_id: UUID,
    http_request: Request,
    current_user: Annotated[AuthenticatedUser, Depends(require_meal_write)],
    session: Annotated[AsyncSession, Depends(get_async_session)],
    settings: Annotated[Settings, Depends(get_settings)],
    request: Annotated[
        MealConfirmationRequest,
        Body(description="User-confirmed food rows for a meal image preview."),
    ],
) -> MealRecordResponse:
    """Confirm a food image preview into a current-user meal record.

    Args:
        meal_id: Meal preview id returned by `/meals/analyze-image`.
        http_request: Current FastAPI request.
        current_user: Authenticated owner.
        session: Request-scoped async database session.
        settings: Application settings.
        request: User-confirmed food rows.

    Returns:
        Confirmed meal record without raw image data.

    Raises:
        HTTPException: If preview ownership, state, or payload validation fails.
    """
    try:
        result = await confirm_meal_record_from_preview(
            session=session,
            user=current_user,
            meal_id=meal_id,
            request=request,
        )
    except MealPreviewNotFoundError as exc:
        await record_sensitive_audit_event(
            session,
            current_user,
            action="meal_image_confirm_missing",
            resource_type="meal_record",
            resource_id=str(meal_id),
            outcome="blocked",
            request=http_request,
            settings=settings,
            event_metadata={"analysis_id_present": request.analysis_id is not None},
        )
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={"code": "meal_preview_not_found", "message": str(exc)},
        ) from exc
    except MealPreviewStateError as exc:
        await record_sensitive_audit_event(
            session,
            current_user,
            action="meal_image_confirm_state_blocked",
            resource_type="meal_record",
            resource_id=str(meal_id),
            outcome="blocked",
            request=http_request,
            settings=settings,
            event_metadata={"analysis_id_present": request.analysis_id is not None},
        )
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail={"code": "meal_preview_not_confirmable", "message": str(exc)},
        ) from exc
    except MealConfirmationValidationError as exc:
        await record_sensitive_audit_event(
            session,
            current_user,
            action="meal_image_confirm_rejected",
            resource_type="meal_record",
            resource_id=str(meal_id),
            outcome="blocked",
            request=http_request,
            settings=settings,
            event_metadata={"analysis_id_present": request.analysis_id is not None},
        )
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail={"code": "meal_confirmation_invalid", "message": str(exc)},
        ) from exc

    response = meal_confirmation_to_response(result)
    await record_sensitive_audit_event(
        session,
        current_user,
        action="meal_image_confirmed",
        resource_type="meal_record",
        resource_id=str(response.id),
        outcome="success",
        request=http_request,
        settings=settings,
        event_metadata={
            "analysis_id_present": request.analysis_id is not None,
            "food_item_count": len(response.food_items),
            "raw_image_stored": False,
            "raw_provider_payload_stored": False,
        },
    )
    return response
