# scripts/install_native_splash.ps1 - Lemon Aid native splash setup
#
# Replaces the default white Flutter splash with our lemon logo splash.
# Uses flutter_native_splash package — generates Android 12+ + iOS native splashes.
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File scripts/install_native_splash.ps1
#
# Requirement:
#   mobile/assets/app_icon/app_icon.png must exist (run install_app_icon.ps1 first)

$ErrorActionPreference = 'Stop'

$RepoRoot = Split-Path -Parent $PSScriptRoot
$MobileDir = Join-Path $RepoRoot 'mobile'
$Pubspec = Join-Path $MobileDir 'pubspec.yaml'
$IconPng = Join-Path $MobileDir 'assets\app_icon\app_icon.png'

Write-Host ""
Write-Host "=================================================="
Write-Host " Lemon Aid Native Splash Installer"
Write-Host "=================================================="
Write-Host ""

if (-not (Test-Path $IconPng)) {
    Write-Host "ERROR: $IconPng not found." -ForegroundColor Red
    Write-Host "Run install_app_icon.ps1 first."
    exit 1
}

# --- pubspec.yaml: add flutter_native_splash to dev_dependencies + config ---
$content = Get-Content -Path $Pubspec -Raw

if ($content -notmatch 'flutter_native_splash:') {
    Write-Host "Adding flutter_native_splash to dev_dependencies..."
    $content = $content -replace '(flutter_launcher_icons: \^0\.13\.1)', "`$1`r`n  flutter_native_splash: ^2.4.1"

    if ($content -notmatch 'flutter_launcher_icons:') {
        # flutter_launcher_icons 가 없으면 flutter_test 옆에 추가
        $content = $content -replace '(dev_dependencies:\s*\r?\n  flutter_test:\s*\r?\n    sdk: flutter)', "`$1`r`n  flutter_native_splash: ^2.4.1"
    }
}

if ($content -notmatch 'flutter_native_splash:\s*\r?\n  color:') {
    Write-Host "Adding flutter_native_splash config..."
    $splashConfig = @'

# Native splash (Android 12+ + iOS LaunchScreen)
# Generated by: dart run flutter_native_splash:create
flutter_native_splash:
  color: "#FEFAE0"
  image: assets/app_icon/app_icon.png
  android_12:
    color: "#FEFAE0"
    image: assets/app_icon/app_icon.png
    icon_background_color: "#FEFAE0"
  ios: true
  android: true
  web: false
  fullscreen: false
  android_gravity: center
  ios_content_mode: center
'@
    $content = $content.TrimEnd() + "`r`n" + $splashConfig + "`r`n"
}

Set-Content -Path $Pubspec -Value $content -NoNewline
Write-Host "  pubspec.yaml updated"

# --- flutter pub get + generate ---
Write-Host ""
Write-Host "Running flutter pub get..."
Push-Location $MobileDir
try {
    flutter pub get
    Write-Host ""
    Write-Host "Generating native splash screens..."
    dart run flutter_native_splash:create
} catch {
    Write-Host "ERROR: $_" -ForegroundColor Red
}
Pop-Location

Write-Host ""
Write-Host "=================================================="
Write-Host " Done. Run 'flutter clean && flutter run' to apply."
Write-Host "=================================================="
Write-Host ""
Write-Host "Background color (#FEFAE0) matches Flutter app background."
Write-Host "User sees: native splash (logo) -> Flutter Splash screen (1.5s) -> Login"
Write-Host ""
