/** 경유지 상태 */
export type WaypointStatus = 'pending' | 'current' | 'completed';

/** 경유지 */
export interface Waypoint {
  poiId: string;
  status: WaypointStatus;
  arrivedAt?: number;
}

/** 세션 상태 */
export type SessionStatus = 'waiting' | 'navigating' | 'completed';

/** QR 토큰 상태 */
export type QRTokenStatus = 'waiting' | 'matched' | 'expired';

/** QR 토큰 (Realtime DB) */
export interface QRToken {
  patientUid: string;
  status: QRTokenStatus;
  sessionId?: string;
  createdAt: number;
  fcmToken?: string;
}

/** 세션 (Realtime DB) */
export interface Session {
  sessionId: string;
  patientUid: string;
  staffUid?: string;
  qrToken: string;
  waypoints: Waypoint[];
  currentWaypointIndex: number;
  status: SessionStatus;
  createdAt: number;
  completedAt?: number;
  hospitalId: string;
  /** 환자 방문 계획 기반으로 생성된 세션 여부 */
  autoGenerated?: boolean;
  /** 계획을 설정한 주체 (autoGenerated=true일 때만 의미) */
  planSource?: 'patient' | 'staff' | 'admin';
}
